import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ExternalLink, ShieldCheck, AlertTriangle } from 'lucide-react';
import { AgentStatusIcon } from './AgentStatusIcon';
import { GPC_DEFINITIONS, type RegionData } from '../types';

interface GpcDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  gpcId?: string;
  regionCode?: string;
  regionData?: RegionData;
}

export const GpcDetailsModal: React.FC<GpcDetailsModalProps> = ({ isOpen, onClose, gpcId, regionCode, regionData }) => {
  const [frozenRegion, setFrozenRegion] = useState<RegionData | null>(null);

  useEffect(() => {
    if (isOpen && regionData) { // Use the passed regionData directly
      setFrozenRegion(regionData);
    } else {
      setFrozenRegion(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, regionData, gpcId]);

  if (!isOpen || !gpcId || !frozenRegion) return null;

  const gpcDetails = GPC_DEFINITIONS.find(g => g.id === gpcId) || { id: gpcId, name: 'Airflow/Python ETL', phaseId: 'PHASE0' };
  const region = frozenRegion;
  const isError = region.state === 'ERROR' && region.currentGpcId === gpcId;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/20 backdrop-blur-sm">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-white border border-slate-200 rounded-2xl shadow-2xl overflow-hidden w-full max-w-2xl flex flex-col"
        >
           <div className={`flex items-center justify-between p-4 border-b ${isError ? 'border-red-200 bg-red-50' : 'border-slate-200 bg-slate-50'}`}>
              <div className="flex items-center gap-3">
                 <div className={`size-8 rounded-lg flex items-center justify-center border shadow-sm ${isError ? 'bg-red-100 text-red-600 border-red-200' : 'bg-blue-50 text-blue-600 border-blue-200'}`}>
                   {isError ? <AlertTriangle size={18} /> : <ShieldCheck size={18} />}
                 </div>
                 <div className="flex flex-col">
                   <h2 className={`text-lg font-bold leading-tight ${isError ? 'text-red-900' : 'text-slate-900'}`}>
                     {gpcDetails.id}: {gpcDetails.name}
                   </h2>
                   <span className={`text-xs font-medium ${isError ? 'text-red-700' : 'text-slate-500'}`}>
                     {isError ? 'Critical Processing Failure' : gpcDetails.phaseId.replace('PHASE', 'Phase ') + ' Controls'}
                   </span>
                 </div>
              </div>
              <div className="flex items-center gap-3">
                 <span className="px-3 py-1 rounded-md text-sm font-mono bg-slate-200 text-slate-700 font-bold shadow-inner">
                   {regionCode}
                 </span>
                 <button 
                   onClick={onClose}
                   className="p-1 hover:bg-slate-200 rounded-full transition-colors text-slate-500 hover:text-slate-900"
                 >
                   <X size={20} />
                 </button>
              </div>
           </div>
           
           <div className="p-6 flex flex-col gap-6">
              <div className="grid grid-cols-2 gap-4">
                 <div className={`flex flex-col gap-1 p-4 rounded-xl border ${isError ? 'bg-red-50/50 border-red-100' : 'bg-slate-50 border-slate-100'}`}>
                   <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider">Status</span>
                   <div className="flex items-center gap-2 mt-1">
                     <AgentStatusIcon state={isError ? 'ERROR' : 'PASSED'} className="size-5" />
                     <span className={`text-sm font-medium ${isError ? 'text-red-700' : 'text-slate-900'}`}>
                       {isError ? 'Rule Validation Failed' : 'Validation Passed'}
                     </span>
                   </div>
                 </div>
                 <div className={`flex flex-col gap-1 p-4 rounded-xl border ${isError ? 'bg-red-50/50 border-red-100' : 'bg-slate-50 border-slate-100'}`}>
                   <span className="text-xs text-slate-500 font-semibold uppercase tracking-wider">ServiceNow Interlock</span>
                   {isError && region?.issueDetails ? (
                      <div className="flex flex-col gap-1 mt-1">
                        <span className="text-sm font-mono font-bold text-red-600">{region.issueDetails.ticketId}</span>
                        <span className="text-[10px] text-red-500 font-medium">Auto-generated by issuehandleragent</span>
                      </div>
                   ) : (
                      <span className="text-sm font-mono text-slate-400 mt-1 italic">Not Triggered</span>
                   )}
                 </div>
              </div>

              <div className="flex flex-col gap-2">
                 <h3 className="text-sm font-bold text-slate-700 border-b border-slate-200 pb-2">Execution Logs</h3>
                 <div className="bg-slate-900 text-slate-300 font-mono text-xs p-4 rounded-lg overflow-y-auto max-h-[200px] leading-relaxed shadow-inner">
                    <p className="text-slate-500">{"[2026-02-21 15:43:02]"} <span className="text-blue-400">INFO</span> Initializing {gpcDetails.id} policy checks...</p>
                    <p className="text-slate-500">{"[2026-02-21 15:43:02]"} <span className="text-blue-400">INFO</span> Fetching region ruleset for {regionCode}</p>
                    
                    {isError ? (
                      <>
                        <p className="text-slate-400">{"[2026-02-21 15:43:03]"} <span className="text-blue-400">INFO</span> Validating 3,402 employee records against rule subset...</p>
                        <p className="text-slate-400">{"[2026-02-21 15:43:03]"} <span className="text-amber-400">WARN</span> 45 record anomalies detected in data buffer.</p>
                        <p className="text-slate-400 bg-red-950/30 py-1">{"[2026-02-21 15:43:04]"} <span className="text-red-500 font-bold">FATAL ERROR</span>: {region?.issueDetails?.description || 'Data missing mandatory parameters.'}</p>
                        <p className="text-slate-400">{"[2026-02-21 15:43:04]"} <span className="text-blue-400">INFO</span> Terminating standard processing queue. Handing off payload to issuehandleragent.</p>
                        <p className="text-slate-400">{"[2026-02-21 15:43:05]"} <span className="text-emerald-500">SYSTEM</span> Ticket {region?.issueDetails?.ticketId || 'INC093848X'} successfully raised in ServiceNow.</p>
                      </>
                    ) : (
                      <>
                        <p className="text-slate-500">{"[2026-02-21 15:43:03]"} <span className="text-emerald-400">SUCCESS</span> Payload structural validation complete (1,492 rows).</p>
                        <p className="text-slate-500">{"[2026-02-21 15:43:03]"} <span className="text-emerald-400">SUCCESS</span> Handshake verified. Awaiting upstream orchestration.</p>
                      </>
                    )}
                 </div>
              </div>

              <div className="flex justify-end pt-2">
                 <button className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 rounded-lg text-sm font-medium transition-colors shadow-sm">
                   <ExternalLink size={16} />
                   View Full Audit Trail
                 </button>
              </div>
           </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
